#!/usr/bin/bash
printf "
APP_NAME='Cybota Analytics Platfom'
APP_ENV=local
APP_KEY=base64:m26eopIlTSzH8IwuQ8r/6wSfyrFlh9h0YwuNaSxhfmA=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=cybota
DB_USERNAME=cveq
DB_PASSWORD=$MYSQL_PASSWORD

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=redis
REDIS_PASSWORD=$REDIS_PASSWORD
REDIS_PORT=6379

MAIL_DRIVER = smtp
MAIL_HOST = $MAIL_HOST
MAIL_PORT = $MAIL_PORT
MAIL_USERNAME = $MAIL_USERNAME
MAIL_PASSWORD = $MAIL_PASSWORD
MAIL_ENCRYPTION = tls

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

JWT_SECRET=l5y91IZOYU896mKtQxQg1RMenegh8iq8xjJb8hLtfh5qCEQNtf7dsaLtndruUyrw


QUEUE_CONNECTION=rabbitmq

RABBITMQ_HOST=rabbitmq
RABBITMQ_PORT=5672
RABBITMQ_VHOST=/
RABBITMQ_LOGIN=$RABBITMQ_USER
RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
RABBITMQ_QUEUE=celery
"
	>> /var/www/html/.env